# netlify.toml — HOTFIX: ensure JSON served from Blobs, not SPA index.html
[build]
  command = "npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  [functions."*"]
    external_node_modules = ["@netlify/blobs", "@supabase/supabase-js"]

# Serve blobs for these prefixes BEFORE SPA catch-all
[[redirects]]
  from = "/picks/*"
  to = "/.netlify/blobs/:splat"
  status = 200

[[redirects]]
  from = "/odds/*"
  to = "/.netlify/blobs/:splat"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
