[build]
  command = "npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs","@supabase/supabase-js"]
  included_files = []

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
